development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: to_drink_development
  pool: 5
  username: postgres
  password:

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: to_drink_test
  pool: 5
  username: postgres
  password:

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: to_drink_production
  pool: 5
  username: postgresql
  password:
